### ISSUE TITLE
2.6.0 fails with gecode-6.3.0: error: too many arguments to function call, expected 4, have 5

### ISSUE THREAD

**Issue by yurivict** [MiniZinc/libminizinc#547]
```
/disk-samsung/freebsd-ports/math/minizinc/work/libminizinc-2.6.0/solvers/gecode/gecode_solverinstance.cpp:1315:81: error: too many arguments to function call, expected 4, have 5
        Driver::CombinedStop::create(nodeStop, failStop, timeStop, restartStop, false);
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                            ^~~~~
/usr/local/include/gecode/driver/script.hpp:92:5: note: 'create' declared here
    create(unsigned long long int node,
    ^
1 error generated.
```

**Comment by yurivict** [comment]
It builds with the latest commits into 2.6.0 branch.
