### ISSUE TITLE
how to build with gecode (5.0.0)

### ISSUE THREAD

**Issue by jwaldmann** [MiniZinc/libminizinc#130]
Hi. How can I build/use minizinc with gecode? INSTALL.txt suggests  `-DGECODE_HOME=<something>`. I don't understand what the argument should denote. Location of unpacked gecode source? Of installed gecode? (Would that be `/usr/local` then?) Of what gecode version (4.4.0 or 5.0.0)? When I try any of these, I get
```
cmake --build .
...
[ 71%] Building CXX object CMakeFiles/minizinc_gecode.dir/solvers/gecode/fzn_space.cpp.o
/home/me/software/constraint/libminizinc/include/minizinc/solvers/gecode_solverinstance.hh:274:13: error: ‘IntConLevel’ in namespace ‘Gecode’ does not name a type
     Gecode::IntConLevel ann2icl(const Annotation& ann);
             ^~~~~~~~~~~
```
From grepping the sources, it seems that `IntContLevel` was present in gecode-4.4.0, but is gone in 5.0.0.

Perhaps it works the other way around (compile gecode with a minizinc back-end)? But when I call
`mzn-gecode`, which appeared after building gecode-5.0.0 from source and installing, I get `line 41: minizinc: command not found`. And the gecode doc refers to flatzinc-1.6 a lot, which is not current?

**Comment by guidotack** [comment]
At the moment you should use the FlatZinc interpreter that comes with Gecode (i.e., just compile Gecode and use the tools/flatzinc/fzn-gecode binary).  We will update the integrated Gecode interface in the next release.

**Comment by jwaldmann** [comment]
I tried, but this segfaults consistently -  http://www.gecode.org/pipermail/users/2017-January/004929.html Am I doing it right?

**Comment by jwaldmann** [comment]
This seems to be working with gecode-6.0.0. 

For reference, a working command line is
```
mzn-fzn -f fzn-gecode software/constraint/minizinc-examples/queens.mzn -Dn=4
```
