### PR TITLE
Add <memory> include required for unique_ptr

### LINKED ISSUE #583: Missing <memory> include for std::unique_ptr in utils.hh
Libminizinc fails to build with GCC 12.1.0:

https://github.com/MiniZinc/libminizinc/blob/f690dc9762b33c06f25dff5202ae9f22b5220cba/include/minizinc/utils.hh#L221

```
[   28s] /usr/bin/c++  -I/home/abuild/rpmbuild/BUILD/libminizinc-2.6.2/include -I/home/abuild/rpmbuild/BUILD/libminizinc-2.6.2/build/include -I/home/abuild/rpmbuild/BUILD/libminizinc-2.6.2/lib/cached -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -g -DNDEBUG -O2 -g -DNDEBUG -fPIC -std=gnu++11 -MD -MT CMakeFiles/minizinc_cplex.dir/solvers/MIP/MIP_cplex_wrap.cpp.o -MF CMakeFiles/minizinc_cplex.dir/solvers/MIP/MIP_cplex_wrap.cpp.o.d -o CMakeFiles/minizinc_cplex.dir/solvers/MIP/MIP_cplex_wrap.cpp.o -c /home/abuild/rpmbuild/BUILD/libminizinc-2.6.2/solvers/MIP/MIP_cplex_wrap.cpp
[   28s] In file included from /home/abuild/rpmbuild/BUILD/libminizinc-2.6.2/solvers/MIP/MIP_cplex_wrap.cpp:18:
[   28s] /home/abuild/rpmbuild/BUILD/libminizinc-2.6.2/include/minizinc/utils.hh:221:15: error: 'unique_ptr' in namespace 'std' does not name a template type
[   28s]   221 |   static std::unique_ptr<OverflowInfo> _ofi;
[   28s]       |               ^~~~~~~~~~
[   28s] /home/abuild/rpmbuild/BUILD/libminizinc-2.6.2/include/minizinc/utils.hh:21:1: note: 'std::unique_ptr' is defined in header '<memory>'; did you forget to '#include <memory>'?
[   28s]    20 | #include <ctime>
[   28s]   +++ |+#include <memory>
[   28s]    21 | #include <iomanip>
```

Log is from libminizinc 2.6.2, but relevant code is unchanged in 2.6.3.

### PR DESCRIPTION
**Pull request by StefanBruens**
Do no rely on <memory> to be included by some other header file.
Fixes build failures with GCC 12.1.0.

Fixes #583.

### CODE REVIEW

**Comment by Dekker1** [comment]
Rebased and merged
